language: rust

cache: cargo

os: linux

matrix:
  include:
    - name: "Clippy & Rustfmt"
      # gfx_device_gl 0.16.1 requires this nightly version
      rust: nightly-2019-08-16
      # Install sound library dependencies
      addons: &addons
        apt:
            packages:
            - libasound2-dev
            - libudev-dev
      env: CLIPPY_REV_SHA=348d398
      before_script:
        - rustup component add rustfmt-preview
        - cargo install --git https://github.com/rust-lang/rust-clippy --rev $CLIPPY_REV_SHA --force clippy
      script:
        - cargo fmt --all -- --check
        - cargo clippy -- -D warnings

    - name: "Stable"
      rust: stable
      addons: *addons

    - name: "Nightly"
      rust: nightly-2019-08-16
      addons: *addons

    - name: "Stable"
      rust: stable
      os: osx

    - name: "Nightly"
      rust: nightly-2019-08-16
      os: osx

script:
  - cargo build --verbose
  - cargo test --verbose

branches:
  only:
    - staging # bors r+
    - trying  # bors try
    - master
