language: rust

cache: cargo

matrix:
  include:
    - rust: nightly
      env: LINT=true SKIP_TESTS=true

    - rust: nightly

    - rust: stable

    - rust: nightly
      os: osx

    - rust: stable
      os: osx

before_install:
  # Update APT for sound library dependencies on linux
  - if [ "$TRAVIS_OS_NAME" = "linux" ] &&
       [ "$SKIP_TESTS" != "true" ] || [ "$LINT" = "true" ]; then
      travis_apt_get_update;
    fi

install:
  - if [ ! -z "$TARGET" ]; then
      rustup target add ${TARGET};
    fi
  # Install sound library dependencies on linux
  - if [ "$TRAVIS_OS_NAME" = "linux" ] &&
         [ "$SKIP_TESTS" != "true" ] || [ "$LINT" = "true" ]; then
      sudo apt-get install libasound2-dev libudev-dev;
    fi

before_script:
  - if [ "$LINT" = "true" ]; then
      rustup component add rustfmt;
      rustup component add clippy || cargo install --force clippy \
        --git https://github.com/rust-lang/rust-clippy;
    fi

script:
  - if [ "$LINT" = "true" ]; then cargo fmt --all -- --check; fi
  - if [ "$LINT" = "true" ]; then cargo clippy -- -D clippy::pedantic; fi
  - if [ "$SKIP_TESTS" != "true" ]; then
      if [ -z "$TARGET" ]; then
        cargo test;
      else
        cargo test --target ${TARGET};
      fi
    fi
