[package]
name = "rustmania"
version = "0.1.0"
authors = ["ixsetf"]
build = "build.rs"

[dependencies]
ggez = "0.4.4"
sdl2 = "0.31.0"
chrono = "0.4.6"
nom = "4.0.0"
num-rational = "0.2.1"
clap = "2.32.0"