[package]
authors = ["ixsetf"]
build = "build.rs"
edition = "2018"
name = "rustmania"
version = "0.1.0"
[dependencies]
chrono = "0.4.6"
clap = "2.32.0"
cpal = "0.8.2"
gfx_core = "0.8.3"
hound = "3.4.0"
lazy_static = "*"
lewton = "0.9.1"
minimp3 = "0.3.0"
nom = "4.1.0"
num-rational = "0.2.1"
regex = "*"
rlua = "0.15.2"
rustyline = "2.1.0"
sdl2 = "0.31.0"
serde = "1.0.79"
serde_derive = "1.0.79"
toml = "0.4.8"
walkdir = "2.2.7"

[dependencies.ggez]
git = "https://github.com/ggez/ggez.git"
