[package]
name = "rustmania"
version = "0.1.0"
authors = ["ixsetf"]
build = "build.rs"
edition = "2018"

[dependencies]
ggez = "0.5.0-rc.0"
sdl2 = "0.31.0"
chrono = "0.4.6"
nom = "4.1.0"
num-rational = "0.2.1"
clap = "2.32.0"
rlua = "0.15.2"
rustyline = "2.1.0"
toml = "0.4.8"
serde_derive = "1.0.79"
serde = "1.0.79"
cpal = "0.8.2"
lewton = "0.9.1"
walkdir = "2.2.7"
minimp3 = "0.3.0"
hound = "3.4.0"
gfx_core = "0.8.3"