[package]
name = "rustmania"
version = "0.1.0"
authors = ["ixsetf"]
build = "build.rs"

[dependencies]
ggez = "0.4.4"
sdl2 = "0.31.0"
chrono = "0.4.6"
nom = "4.0.0"
num-rational = "0.2.1"
clap = "2.32.0"
rlua = "0.14.2"
rustyline = "2.1.0"
toml = "0.4.6"
serde_derive = "1.0.79"
serde = "1.0.79"
cpal = "0.8.2"